stages:
  - install
  - test
  - publish-docker-image
  - dev-deploy

default:
  image: node:18 #TODO - use node:18-alipne, but install openSLL, otherwise prisma job will fail

.standard-rules: # Make a hidden job to hold the common rules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

install-deps:
  stage: install
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
  script:
    - npm install
    - npx prisma generate

run-tests-with-coverage:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
  needs:
    - install-deps
  script:
    - npx prisma generate
    - npm run test:cov

run-linter:
  stage: test
  needs:
    - install-deps
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
  script:
    - npm run lint
  allow_failure: true

build-docker-image:
  image: docker:latest
  stage: publish-docker-image
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      exists:
        - docker-compose.yml
      when: always
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo $ENV_FILE
    # File is outside of build context, so make local copy.
    - cp $ENV_FILE .env
    - docker compose up --build -dV
    - docker tag looties-api-dev:latest "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"

deploy-to-dev:
  stage: dev-deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
  needs:
    - build-docker-image
  script:
    - echo "Dummy deploy to dev"