stages:
  - install
  - test
  - dev-deploy

default:
  image: node:18

#Jobs that start with . are hidden from the runner
.standard-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

install-deps:
  stage: install
  extends:
    - .standard-rules
  script:
    - npm install

run-tests-with-coverage:
  stage: test
  needs:
    - install-deps
  extends:
    - .standard-rules
  script:
    - npm run test:cov

run-linter:
  stage: test
  needs:
    - install-deps
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - npm run lint
  allow_failure: true

deploy-to-dev:
  stage: dev-deploy
  needs:
    - run-tests-with-coverage
    - run-linter
  extends:
    - .standard-rules
  script:
    - echo "Dummy deploy to dev"