version: '3.8'

services:
  nest-api:
    container_name: looties-api
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    env_file:
        - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@looties-postgres:5432/${POSTGRES_DB}?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    # Run in dev Mode: npm run start:dev
    command: npm run start:migrate:dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - pgadmin

  postgres:
    container_name: looties-postgres
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: looties-pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  postgres:
    name: looties-postgres
  pgadmin:
    name: looties-pgadmin